### ISSUE TITLE
ibmcloudsql - node...

### ISSUE THREAD

**Issue by ethilesen** [IBM-Cloud/sql-query-clients#101]
Hi,

Anyone maintaining this ?

**Comment by torsstei** [comment]
@ethilesen you mean the node SDK specifically? Not really. We're planning to release a new node SDK soon though.

The Python in this repo though is very actively maintained by me.

**Comment by ethilesen** [comment]
@torsstei yes that was I was testing out for a client demo and ended up fiks it to work but it's a lot more to do there so a new one are more than welcome :) The python stuff works perfect but I had this client that wanted to do some simple stuff from node..
But  tanks...

**Comment by torsstei** [comment]
@ethilesen Please check this out: https://github.com/IBM/sql-query-node-sdk
