### ISSUE TITLE
get_result return failure if result is deleted

### ISSUE THREAD

**Issue by mvle** [IBM-Cloud/sql-query-clients#24]
Result object might have been deleted due to call to `delete_result`. If this is the case, the call to `get_result` will throw exception of undefined `result_df`. Fix should be to define `result_df` before hand.

**Comment by torsstei** [comment]
OK @mvle . Fixed with https://github.com/IBM-Cloud/sql-query-clients/commit/9d843000b3782d278135d814cea1a8047a0e6192 and published in v 0.2.16.
