### ISSUE TITLE
urllib.urlencode is not compatible with Python 3

### ISSUE THREAD

**Issue by aa7955** [IBM-Cloud/sql-query-clients#3]
https://github.com/IBM-Cloud/sql-query-clients/blob/1c973d5d1d27dab4840dd98798bfbd8be4bbf616/Python/ibmcloudsql/SQLQuery.py#L54

**Comment by torsstei** [comment]
Thanks. The issue is now fixed and I tested successfully with both, Python2 and Python3. New v 0.1.3 on pypi.
