### ISSUE TITLE
New feature: automatic wait and retry when hitting request rate limit

### ISSUE THREAD

**Issue by shawnzhu** [IBM-Cloud/sql-query-clients#63]
**Is your feature request related to a problem? Please describe.**
When there're 5 concurrent query jobs running, the 6th request will fail with an exception after fixing #59. which makes sense, however, it leaves client side code to do retry.

**Describe the solution you'd like**
It would be great if there's builtin feature to support wait and retry automatically once hitting request rate limit (status code 429). And this new feature can be turned off first, once it's stable then can be turned on by default.

It would also need to reference how such problem is handled in other cloud API sdks.

**Describe alternatives you've considered**
Without a builtin feature, it would be great to document such case w/o code change.

**Additional context**
#59

**Comment by cullinap** [comment]
@shawnzhu I would also like to see this. When this is running in jupyter notebooks as part of a greater pipeline I get a RateLimitedException, which stops the notebook and forces me to rerun it. In this case is it possible to wait until compute resources are available and run it just like the wait_for_job method does?

**Comment by torsstei** [comment]
@cullinap We should get this automatic retry done shortly. FYI, in case you frequently run against the 5 concurrent query limit per SQL Query instance, you can request the limit to be increased for your instance if you can make the case that your workload is sustainably exceeding this limit.

**Comment by shawnzhu** [comment]
I will use implement retry logic by using [Exponential backoff](https://en.wikipedia.org/wiki/Exponential_backoff) first.

Performance of such automatic retry can be improved by using response headers when getting status code `429`. E.g., via header `X-RateLimit-Reset` and `X-RateLimit-Remaining` from [Rate Limiting](https://cloud.ibm.com/apidocs/enterprise-apis/enterprise#rate-limiting).

**Comment by shawnzhu** [comment]
## Design

After merging #65

By default, there's no backoff when getting response code `429`.

As a user who needs automatic retry, it can do:

```Python
# create a client with up to 10 tries when request hit rate limits. 
sql_client = SQLQuery('api-key', 'instance-crn', max_tries=10)
```
